<?php
return array (
  'enabled' => true,
  'is_admin' => true,
  'language' => 'en',
  'timezone' => '',
  'archiving' => 
  array (
    'keep_period' => 'P3M',
    'keep_max' => 200,
    'keep_min' => 50,
    'keep_favourites' => true,
    'keep_labels' => true,
    'keep_unreads' => false,
  ),
  'ttl_default' => 3600,
  'dynamic_opml_ttl_default' => 43200,
  'mail_login' => '',
  'email_validation_token' => '',
  'token' => '',
  'passwordHash' => '$2a$09$YC5IhvEVUo/LxdTpcFVyf.z1.hX3iZix9UZg7Y4kOgcPVfNfFc2tW',
  'apiPasswordHash' => '',
  'feverKey' => '',
  'posts_per_page' => 20,
  'since_hours_posts_per_rss' => 168,
  'max_posts_per_rss' => 400,
  'view_mode' => 'normal',
  'default_view' => 'adaptive',
  'default_state' => 2,
  'show_fav_unread' => false,
  'auto_load_more' => true,
  'display_posts' => false,
  'display_categories' => 'active',
  'show_tags' => 'f',
  'show_tags_max' => 7,
  'show_author_date' => 'h',
  'show_feed_name' => 'a',
  'show_article_icons' => 't',
  'hide_read_feeds' => true,
  'onread_jump_next' => true,
  'lazyload' => true,
  'sides_close_article' => false,
  'sticky_post' => true,
  'reading_confirm' => false,
  'auto_remove_article' => false,
  'mark_updated_article_unread' => false,
  'sort_order' => 'DESC',
  'anon_access' => false,
  'mark_when' => 
  array (
    'article' => true,
    'gone' => false,
    'max_n_unread' => false,
    'reception' => false,
    'same_title_in_feed' => false,
    'scroll' => false,
    'focus' => false,
    'site' => true,
  ),
  'filters' => 
  array (
  ),
  'theme' => 'Origine',
  'darkMode' => 'auto',
  'content_width' => 'thin',
  'shortcuts' => 
  array (
    'actualize' => 'q',
    'mark_read' => 'r',
    'mark_favorite' => 'f',
    'go_website' => 'space',
    'next_entry' => 'j',
    'next_unread_entry' => 'h',
    'prev_entry' => 'k',
    'skip_next_entry' => 'n',
    'skip_prev_entry' => 'p',
    'first_entry' => 'home',
    'last_entry' => 'end',
    'collapse_entry' => 'c',
    'load_more' => 'm',
    'auto_share' => 's',
    'focus_search' => 'a',
    'user_filter' => 'u',
    'help' => 'f1',
    'close_dropdown' => 'escape',
    'normal_view' => '1',
    'global_view' => '2',
    'reading_view' => '3',
    'toggle_media' => 'v',
  ),
  'show_favicons' => true,
  'icons_as_emojis' => false,
  'simplify_over_n_feeds' => 1000,
  'topline_read' => true,
  'topline_favorite' => true,
  'topline_myLabels' => false,
  'topline_sharing' => false,
  'topline_website' => 'full',
  'topline_thumbnail' => 'none',
  'topline_summary' => false,
  'topline_display_authors' => false,
  'topline_date' => true,
  'topline_link' => true,
  'bottomline_read' => true,
  'bottomline_favorite' => true,
  'bottomline_sharing' => true,
  'bottomline_tags' => true,
  'bottomline_myLabels' => true,
  'bottomline_date' => true,
  'bottomline_link' => true,
  'sharing' => 
  array (
  ),
  'queries' => 
  array (
    0 => 
    array (
      'get' => 'f_9',
      'name' => 'APPSEC',
      'order' => 'DESC',
      'search' => 'intitle:[app]',
      'state' => 15,
      'url' => './?get=f_9&amp;order=DESC&amp;search=intitle%3A%5Bapp%5D&amp;state=15&amp;token=4Ftv9auoZMNlCguYReTDA1',
      'token' => '4Ftv9auoZMNlCguYReTDA1',
      'description' => 'Talkback APPSEC tag',
    ),
    1 => 
    array (
      'get' => 'f_9',
      'name' => 'CLOUDSEC',
      'order' => 'DESC',
      'search' => 'intitle:[cloud]',
      'state' => 15,
      'url' => './?get=f_9&amp;order=DESC&amp;search=intitle%3A%5Bcloud%5D&amp;state=15&amp;token=73zLMDVJzwkOrhj3xMBQsA',
      'token' => '73zLMDVJzwkOrhj3xMBQsA',
      'description' => 'Tackback CLOUDSEC tag',
    ),
    2 => 
    array (
      'get' => 'c_5',
      'name' => 'EXPLOIT',
      'order' => 'DESC',
      'search' => 'intitle:[exp]',
      'state' => 15,
      'url' => './?get=c_5&amp;order=DESC&amp;search=intitle%3A%5Bexp%5D&amp;state=15&amp;token=1vsIATjCwlR0t2aXEp3dwm',
      'token' => '1vsIATjCwlR0t2aXEp3dwm',
      'description' => 'Talkback EXPLOIT tag',
    ),
    3 => 
    array (
      'get' => 'a',
      'name' => 'FORENSICS',
      'order' => 'DESC',
      'search' => 'intitle:[for]',
      'state' => 15,
      'url' => './?get=a&amp;order=DESC&amp;search=intitle%3A%5Bfor%5D&amp;state=15&amp;token=6ZNFpQZkDhhYOimQuUJGFg',
      'token' => '6ZNFpQZkDhhYOimQuUJGFg',
      'description' => 'Talkback FORENSICS tag',
    ),
    4 => 
    array (
      'get' => 'f_9',
      'name' => 'INDUSTRIAL SYSTEMS',
      'order' => 'DESC',
      'search' => 'intitle:[ics]',
      'state' => 15,
      'url' => './?get=f_9&amp;order=DESC&amp;search=intitle%3A%5Bics%5D&amp;state=15&amp;token=2sWRnnYZ5wKMA1SplNFkvf',
      'token' => '2sWRnnYZ5wKMA1SplNFkvf',
      'description' => 'Talkback INDUSTRIAL CONSTROL SYSTEMS tag',
    ),
    5 => 
    array (
      'get' => 'a',
      'name' => 'NETSEC',
      'order' => 'DESC',
      'search' => 'intitle:[net]',
      'state' => 15,
      'url' => './?get=a&amp;order=DESC&amp;search=intitle%3A%5Bnet%5D&amp;state=15&amp;token=5126gIG5pgKRsaMHhPXeir',
      'token' => '5126gIG5pgKRsaMHhPXeir',
      'description' => 'Talkback NETSEC tag',
    ),
    6 => 
    array (
      'get' => 'a',
      'name' => 'REVERSE',
      'order' => 'DESC',
      'search' => 'intitle:[rev]',
      'state' => 15,
      'url' => './?get=a&amp;order=DESC&amp;search=intitle%3A%5Brev%5D&amp;state=15&amp;token=3Yx6nDNmMncueYuF05gBEh',
      'token' => '3Yx6nDNmMncueYuF05gBEh',
      'description' => 'Talkback REVERSE ENGINEERING tag',
    ),
    7 => 
    array (
      'get' => 'a',
      'name' => 'SOCIAL',
      'order' => 'DESC',
      'search' => 'intitle:[social]',
      'state' => 15,
      'url' => './?get=a&amp;order=DESC&amp;search=intitle%3A%5Bsocial%5D&amp;state=15&amp;token=4puC8OgGlSD8phFuSgNaPA',
      'token' => '4puC8OgGlSD8phFuSgNaPA',
      'description' => 'Talkback SOCIAL ENGINEERING tag',
    ),
    8 => 
    array (
      'get' => 'a',
      'name' => 'SYSTEMS',
      'order' => 'DESC',
      'search' => 'intitle:[sys]',
      'state' => 15,
      'url' => './?get=a&amp;order=DESC&amp;search=intitle%3A%5Bsys%5D&amp;state=15&amp;token=348MDtxIRCPdiaDwmHq5Uq',
      'token' => '348MDtxIRCPdiaDwmHq5Uq',
      'description' => 'Talkback SYSTEMS tag',
    ),
    9 => 
    array (
      'name' => 'Query n°10',
      'search' => 'intitle:[mal]',
      'url' => './?search=intitle%3A%5Bmal%5D',
    ),
  ),
  'html5_notif_timeout' => 0,
  'show_nav_buttons' => true,
  'extensions_enabled' => 
  array (
  ),
  'retrieve_extension_list' => true,
  'extensions' => 
  array (
  ),
);